name: 'GitHub Actions Email Actions By bin4xin'

on: [workflow_dispatch]

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Send Email'
        run: bash ./SCS_domail_mail_manage.sh ${{secrets.SENTRY_MAIL_PDDTOKEN}} UserName # <修改这里.>最后一个字段为您的用户名
      - name: 'Get Some Value'
        run: |
          echo "REPORT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "REPORT_PLACE=$(curl -sL ip.tool.lu |awk -F ":" '{print $2}'|awk 'NR==2')" >> $GITHUB_ENV
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.yandex.com
          server_port: 465
          username: ${{secrets.SENTRY_MAIL_USERNAME}}
          password: ${{secrets.SENTRY_MAIL_PASSWORD}}
          subject: "您的订阅信息"
          html_body: file://result.html
          to: your_email@domain.com # <修改这里.>接收您账号密码的邮箱
          from: 哨兵
          content_type: text/html
