name: 'GitHub Actions Email Actions By bin4xin'

on:
  push:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Send Email'
        run: bash ./processEmail.sh
      - name: 'Get Date'
        run: echo "REPORT_PLACE=$(curl -sL ip.tool.lu |awk -F ":" '{print $2}'|awk 'NR==2')" >> $GITHUB_ENV
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Github Actions - ${{ env.REPORT_PLACE }} Machine"
          html_body: file://result.html
          to: 1904829268@qq.com
          cc: chihou.pro@gmail.com
          from: 哨兵
          content_type: text/html
