name: 'GitHub Actions Email Actions By bin4xin'

on: [push]
#  push:
#  schedule:
#    - cron: '0 */6 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Send Email'
        run: bash ./processEmail.sh
      - name: 'Get Some Value'
        run: |
          echo "REPORT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "REPORT_PLACE=$(curl -sL ip.tool.lu |awk -F ":" '{print $2}'|awk 'NR==2')" >> $GITHUB_ENV
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.zoho.com.cn
          server_port: 465
          #username: ${{ secrets.MAIL_USERNAME }}
          #password: ${{ secrets.MAIL_PASSWORD }}
          username: ${{ secrets.SENTRY_MAIL_USERNAME }}
          password: ${{ secrets.SENTRY_MAIL_PASSWORD }}
          subject: "${{ env.REPORT_PLACE }} - 订阅信息"
          html_body: file://result.html
          to: 2635641640@qq.com
          cc: chihou.pro@gmail.com
          from: 哨兵 -  ${{ env.REPORT_COMMIT }}
          content_type: text/html